version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - pip-cache:/root/.cache/pip
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pip-cache:
